-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 23:24:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todotrabajo
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema todotrabajo
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todotrabajo` DEFAULT CHARACTER SET utf8 ;
USE `todotrabajo` ;

-- -----------------------------------------------------
-- Table `todotrabajo`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`persona` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `tarjeta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`),
  UNIQUE INDEX `rut_UNIQUE` (`rut` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`usuario` (
  `idusuario` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `tipoUsuario` VARCHAR(45) NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`, `rut`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_usuario_persona_idx` (`rut` ASC) ,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`rut`)
    REFERENCES `todotrabajo`.`persona` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`publicacion` (
  `idpublicacion` INT NOT NULL,
  `descripción` VARCHAR(45) NULL,
  `aPagar` VARCHAR(45) NULL,
  `ubicación` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpublicacion`, `idusuario`, `rut`),
  INDEX `fk_publicacion_usuario1_idx` (`idusuario` ASC, `rut` ASC),
  CONSTRAINT `fk_publicacion_usuario1`
    FOREIGN KEY (`idusuario` , `rut`)
    REFERENCES `todotrabajo`.`usuario` (`idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`pregunta` (
  `idpregunta` INT NOT NULL,
  `texto` VARCHAR(45) NULL,
  `idpublicacion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpregunta`, `idpublicacion`, `idusuario`, `rut`),
  INDEX `fk_pregunta_publicacion1_idx` (`idpublicacion` ASC, `idusuario` ASC, `rut` ASC),
  CONSTRAINT `fk_pregunta_publicacion1`
    FOREIGN KEY (`idpublicacion` , `idusuario` , `rut`)
    REFERENCES `todotrabajo`.`publicacion` (`idpublicacion` , `idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`respuesta` (
  `idrespuesta` INT NOT NULL,
  `texto` VARCHAR(45) NULL,
  `idpregunta` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`, `idpregunta`),
  INDEX `fk_respuesta_pregunta1_idx` (`idpregunta` ASC),
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`idpregunta`)
    REFERENCES `todotrabajo`.`pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`experiencia` (
  `idexperiencia` INT NOT NULL,
  `esRealizado` INT NULL,
  `esPostulado` INT NULL,
  `puntos` VARCHAR(45) NULL,
  `esSubido` INT NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idexperiencia`, `idusuario`, `rut`),
  INDEX `fk_experiencia_usuario1_idx` (`idusuario` ASC, `rut` ASC),
  CONSTRAINT `fk_experiencia_usuario1`
    FOREIGN KEY (`idusuario` , `rut`)
    REFERENCES `todotrabajo`.`usuario` (`idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`destacado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`destacado` (
  `iddestacado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidoM` VARCHAR(45) NULL,
  `apellidoP` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddestacado`, `idusuario`, `rut`),
  INDEX `fk_destacado_usuario1_idx` (`idusuario` ASC, `rut` ASC),
  CONSTRAINT `fk_destacado_usuario1`
    FOREIGN KEY (`idusuario` , `rut`)
    REFERENCES `todotrabajo`.`usuario` (`idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`etiqueta` (
  `idetiqueta` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `texto` VARCHAR(45) NULL,
  PRIMARY KEY (`idetiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`postulante` (
  `idpostulante` INT NOT NULL,
  `experiencia` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidoP` VARCHAR(45) NULL,
  `apellidoA` VARCHAR(45) NULL,
  PRIMARY KEY (`idpostulante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`postulacion` (
  `idpostulante` INT NOT NULL,
  `idpublicacion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpostulante`, `idpublicacion`, `idusuario`, `rut`),
  INDEX `fk_postulante_has_publicacion_publicacion1_idx` (`idpublicacion` ASC, `idusuario` ASC, `rut` ASC),
  INDEX `fk_postulante_has_publicacion_postulante1_idx` (`idpostulante` ASC),
  CONSTRAINT `fk_postulante_has_publicacion_postulante1`
    FOREIGN KEY (`idpostulante`)
    REFERENCES `todotrabajo`.`postulante` (`idpostulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_has_publicacion_publicacion1`
    FOREIGN KEY (`idpublicacion` , `idusuario` , `rut`)
    REFERENCES `todotrabajo`.`publicacion` (`idpublicacion` , `idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`seleccionado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`seleccionado` (
  `idseleccionado` INT NOT NULL,
  `esEnviado` VARCHAR(45) NULL,
  `numEnviado` VARCHAR(45) NULL,
  `idpostulante` INT NOT NULL,
  `idpublicacion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idseleccionado`, `idpostulante`, `idpublicacion`, `idusuario`, `rut`),
  INDEX `fk_seleccionado_postulante_has_publicacion1_idx` (`idpostulante` ASC, `idpublicacion` ASC, `idusuario` ASC, `rut` ASC),
  CONSTRAINT `fk_seleccionado_postulante_has_publicacion1`
    FOREIGN KEY (`idpostulante` , `idpublicacion` , `idusuario` , `rut`)
    REFERENCES `todotrabajo`.`postulacion` (`idpostulante` , `idpublicacion` , `idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todotrabajo`.`etiquetacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todotrabajo`.`etiquetacion` (
  `idetiqueta` INT NOT NULL,
  `idpublicacion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idetiqueta`, `idpublicacion`, `idusuario`, `rut`),
  INDEX `fk_etiqueta_has_publicacion_publicacion1_idx` (`idpublicacion` ASC, `idusuario` ASC, `rut` ASC),
  INDEX `fk_etiqueta_has_publicacion_etiqueta1_idx` (`idetiqueta` ASC) ,
  CONSTRAINT `fk_etiqueta_has_publicacion_etiqueta1`
    FOREIGN KEY (`idetiqueta`)
    REFERENCES `todotrabajo`.`etiqueta` (`idetiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiqueta_has_publicacion_publicacion1`
    FOREIGN KEY (`idpublicacion` , `idusuario` , `rut`)
    REFERENCES `todotrabajo`.`publicacion` (`idpublicacion` , `idusuario` , `rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
